services:
  - type: web
    name: api-gohan
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        fromContext: environment
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: BASE_URL
        sync: false
